### ISSUE TITLE
React components are just plain white, not highlighted

### ISSUE THREAD

**Issue by medmin** [akarlsten/adam-snazzy-vscode#1]
Hi, there

So, I have noticed that React componets are not highlighted.

```javascript

const MyComponent = ({msg})=>(<div>{msg}</div>);

function App(){
   
    return (
        <MyComponent msg="Hello World" />
     );  

}

```

In the above code, `MyComponent` is just white, not highlighted.

Is there any way to make it colorful ? Thanks

**Comment by akarlsten** [comment]
What language setting do you have set for the file? 

With Javascript (Babel) I get highlighting as if the component were a HTML element (which is what I want):
![Screenshot_20191204_151931](https://user-images.githubusercontent.com/13545738/70150112-bc244880-16a9-11ea-990c-8c18920091da.png)

**Comment by medmin** [comment]
Thanks. Yeah, that's what i need too. May i ask how you set it ? Would you like to share your settings ? Thanks.
