### ISSUE TITLE
Add some instructions on how to override colors

### ISSUE THREAD

**Issue by 0x80** [akarlsten/adam-snazzy-vscode#2]
I think it would be helpful if you added some instructions on how to override colors.

For example, I love the Plus w/ Italics theme, but the comments were simply too dark for me. In my repo the comments are usually important so want to see them clearly.

This is how I changed it using VSCode settings.

```json
"editor.tokenColorCustomizations": {
    "[Snazzy Plus w/ Italics]":{
      "comments": "#aaa",
    },
  },
```

**Comment by akarlsten** [comment]
Good idea, I've added it to the README! 👍
